apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongo-pv
  labels:
    environment: dev
spec:
  capacity:
    storage: 500Mi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  local:
    path: /mnt/data/
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - worker-node-1

#  mountOptions:
#    - hard
#    - nfsvers=4.1
#  nfs:
#    path: "/media/tayo/UBUNTU 24_0/dists" #NFS path that was exported
#    server: 192.168.100.213 #IP of the nfs server
