resources:
  - ./../../../base

namePrefix: actual-

commonLabels:
  version: old

images:
  - name: tayofere/client
    newTag: v1.0.0
  - name: tayofere/nodeapi
    newTag: v1.0.0
  - name: tayofere/javaapi
    newTag: v1.0.0

replicas:
  - name: client-deploy
    count: 2
  - name: api-deploy
    count: 2
  - name: webapi-deploy
    count: 2