apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapi-deployment
  namespace: emart-app
  labels:
    app: webapi-deployment-label
spec:
  replicas: 2
  selector:
    matchLabels:
      app: webapi-pod
  template:
    metadata:
      labels:
        app: webapi-pod
    spec:
      containers:
      - name: webapi-container
        image: tayofere/javaapi:16
        ports:
        - containerPort: 9000
          name: webapi-port
---
apiVersion: v1
kind: Service
metadata:
  name: webapi-svc
  namespace: emart-app
spec:
  selector:
    app: webapi-pod
  ports:
  - protocol: TCP
    port: 9000
    targetPort: webapi-port