apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deploy
  namespace: emart-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-pod
  template:
    metadata:
      labels:
        app: api-pod
    spec:
      # serviceAccountName: aws-secret-sa
      # imagePullSecrets:
      # - name: ghcr-secret
      terminationGracePeriodSeconds: 120
      restartPolicy: Always
      # volumes:
      # - name: secrets-store-inline
      #   csi:
      #     driver: secrets-store.csi.k8s.io
      #     readOnly: true
      #     volumeAttributes:
      #       secretProviderClass: aws-secrets
      containers:
      - name: api-container
        image: 074360085759.dkr.ecr.us-east-1.amazonaws.com/omotayoofere/node-api:sha-3d0426b
        ports:
        - containerPort: 5000
          name: api-port
        resources:
          requests:
            cpu: "0.2"
            memory: "100Mi"
          limits:
            cpu: "0.2"
            memory: "100Mi"
        # volumeMounts:
        #     - name: secrets-store-inline
        #       mountPath: /mnt/secrets
        #       readOnly: true
        readinessProbe:
          tcpSocket:
            port: api-port
          initialDelaySeconds: 10
          periodSeconds: 5
          failureThreshold: 5
        livenessProbe:
          tcpSocket:
            port: api-port
          initialDelaySeconds: 5
          periodSeconds: 10
          failureThreshold: 10
        startupProbe:
          tcpSocket:
            port: api-port
          initialDelaySeconds: 5
          periodSeconds: 10
          failureThreshold: 3

---
apiVersion: v1
kind: Service
metadata:
  name: api-svc
  namespace: emart-app
spec:
  selector:
    app: api-pod
  ports:
  - protocol: TCP
    port: 5000
    targetPort: api-port
