apiVersion: apps/v1
kind: Deployment
metadata:
  name: kibana
  namespace: logging
spec:
  selector:
    matchLabels:
      app: kibana-pod
  serviceName: "kibana-svc"
  replicas: 1
  minReadySeconds: 10
  template:
    metadata:
      labels:
        app: kibana-pod
    spec:
      restartPolicy: Always
      terminationGracePeriodSeconds: 120
      containers:
      - name: kibana-container
        image: docker.elastic.co/kibana/kibana:7.17.0
        resources:
          requests:
            cpu: "0.5"
            memory: "100Mi"
          limits:
            cpu: "0.5"
            memory: "100Mi"
        env:
          - name: ELASTICSEARCH_HOSTS
            value: http://elasticsearch-svc:9200
        ports:
          - containerPort: 5601
            name: kibana-port
        readinessProbe:
          tcpSocket:
            port: kibana-port
          initialDelaySeconds: 10
          periodSeconds: 5
          failureThreshold: 5
        livenessProbe:
          tcpSocket:
            port: kibana-port
          initialDelaySeconds: 5
          periodSeconds: 10
          failureThreshold: 10
        startupProbe:
          tcpSocket:
            port: kibana-port
          initialDelaySeconds: 5
          periodSeconds: 10
          failureThreshold: 3
        
---
apiVersion: v1
kind: Service
metadata:
  name: kibana-svc
  namespace: logging
spec:
  clusterIP: None
  selector:
    app: kibana-pod
  ports:
  - protocol: TCP
    port: 5601
    targetPort: kibana-port