apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  appName: emart-app
  app.kubernetes.io/managed-by: kustomize

resources:
- mongo-pvc.yaml
- mongo-pv.yaml
- cluster-secret-store.yaml
- monitor-tls-secret.yaml
- emart-tls-secret.yaml
- emartdbdeploy.yaml
- emongodbdeploy.yaml
- apideploy.yaml
- webapideploy.yaml
- clientdeploy.yaml
- appingress.yaml
- prom-ingress.yaml