apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-pvc
  namespace: emart-app
spec:
  storageClassName: ebs-sc # Empty string must be explicitly set otherwise default StorageClass will be set
  # volumeName: mongo-pv
  # volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  # selector:
  #   matchLabels:
  #     environment: "dev"