resources:
  - ./../../../base

namePrefix: canary-

commonLabels:
  version: new

images:
  - name: tayofere/client
 newTag:26
  - name: tayofere/nodeapi
 newTag:26
  - name: tayofere/javaapi
 newTag:26

replicas:
  - name: client-deploy
    count: 1
  - name: api-deploy
    count: 1
  - name: webapi-deploy
    count: 1