resources:
  - ./../../../base

namePrefix: canary-

commonLabels:
  version: new

images:
  - name: tayofere/client
newTag: 64
  - name: tayofere/nodeapi
newTag: 64
  - name: tayofere/javaapi
newTag: 64

replicas:
  - name: client-deploy
    count: 1
  - name: api-deploy
    count: 1
  - name: webapi-deploy
    count: 1