name: Build, Test and deploy Emart App
on:
  push:
    branches:
      - main
jobs:
  build:
    name: Checkout REPO and containerize applications
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5.0.0
        with:
          repository: ${{ vars.REPO_URL }}
          ref: ${{ vars.REPO_BRANCH }}
          token: ${{ secrets.REPO_TOKEN }}
          fetch-tags: true
          lfs: true
          
      - name: Print Build Metadata
        id: build_data
        run: | 
          echo "commit_hash=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
          echo "timestamp=$(date +%Y%m%d%H%M%S)" >> $GITHUB_OUTPUT
          echo "build_number=${{ github.run_number }}" >> $GITHUB_OUTPUT
          
      - name: Docker Credentials
        uses: docker/login-action@v3.5.0
        with: 
          username: ${{ vars.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Docker Build and Push
        run: |
          apps="client nodeapi javaapi"
          
          for dir in ${apps[@]};
          do
            echo "Subdirs of $dir:"
            find "$dir" -mindepth 1 -maxdepth 1 -type d 
          done

          
        
          #docker build -t $IMAGE_NAME:latest .
          #docker tag $IMAGE_NAME:latest $IMAGE_NAME:${{ steps.vars.outputs.commit_hash }}
          #docker tag $IMAGE_NAME:latest $IMAGE_NAME:${{ steps.vars.outputs.timestamp }}
          #docker tag $IMAGE_NAME:latest $IMAGE_NAME:${{ steps.vars.outputs.build_number }}

          #docker push -t $IMAGE_NAME:latest .
          #docker push $IMAGE_NAME:latest $IMAGE_NAME:${{ steps.vars.outputs.commit_hash }}
          #docker push $IMAGE_NAME:latest $IMAGE_NAME:${{ steps.vars.outputs.timestamp }}
          #docker push $IMAGE_NAME:latest $IMAGE_NAME:${{ steps.vars.outputs.build_number }}
      #- name: Containerize App
      #  uses: docker/build-push-action@v6.18.0
      #  with: 
